export enum ECurrencyExchange {
  USD = 'USD',
  EUR = 'EUR',
  BRL = 'BRL',
  JPY = 'JPY',
  GBP = 'GBP',
  AUD = 'AUD',
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  NZD = 'NZD',
  SEK = 'SEK',
  NOK = 'NOK',
  KRW = 'KRW',
  SGD = 'SGD',
  HKD = 'HKD',
  INR = 'INR',
}

export enum ECurrencyExchangeTranslate {
  USD = 'US Dollar',
  EUR = 'Euro',
  BRL = 'Brazillian Real',
  JPY = 'Japanese Yen',
  GBP = 'British Pound',
  AUD = 'Australian Dollar',
  CAD = 'Canadian Dollar',
  CHF = 'Swiss Franc',
  CNY = 'Chinese Yuan (Renminbi)',
  NZD = 'New ZealandDollar',
  SEK = 'Swedish Krona',
  NOK = 'Norwegian Krone',
  KRW = 'South Korean Won',
  SGD = 'Singapore Dollar',
  HKD = 'Hong Kong Dollar',
  INR = 'Indian Rupee',
}
